/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualQueueGuideRouteImport } from './routes/virtual-queue-guide'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BootstrapAdminRouteImport } from './routes/bootstrap-admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorInviteAcceptRouteImport } from './routes/doctor-invite.accept'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BlogVirtualVsPhysicalQueuesRouteImport } from './routes/blog.virtual-vs-physical-queues'
import { Route as AuthenticatedPendingActivationRouteImport } from './routes/_authenticated/pending-activation'
import { Route as AuthenticatedManagementRouteImport } from './routes/_authenticated/management'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedManagementIndexRouteImport } from './routes/_authenticated/management.index'
import { Route as AuthenticatedManagementHistoryRouteImport } from './routes/_authenticated/management.history'

const VirtualQueueGuideRoute = VirtualQueueGuideRouteImport.update({
  id: '/virtual-queue-guide',
  path: '/virtual-queue-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapAdminRoute = BootstrapAdminRouteImport.update({
  id: '/bootstrap-admin',
  path: '/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorInviteAcceptRoute = DoctorInviteAcceptRouteImport.update({
  id: '/doctor-invite/accept',
  path: '/doctor-invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogVirtualVsPhysicalQueuesRoute =
  BlogVirtualVsPhysicalQueuesRouteImport.update({
    id: '/blog/virtual-vs-physical-queues',
    path: '/blog/virtual-vs-physical-queues',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPendingActivationRoute =
  AuthenticatedPendingActivationRouteImport.update({
    id: '/pending-activation',
    path: '/pending-activation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementRoute = AuthenticatedManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagementIndexRoute =
  AuthenticatedManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementHistoryRoute =
  AuthenticatedManagementHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bootstrap-admin': typeof BootstrapAdminRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/virtual-queue-guide': typeof VirtualQueueGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/management': typeof AuthenticatedManagementRouteWithChildren
  '/pending-activation': typeof AuthenticatedPendingActivationRoute
  '/blog/virtual-vs-physical-queues': typeof BlogVirtualVsPhysicalQueuesRoute
  '/book/$slug': typeof BookSlugRoute
  '/doctor-invite/accept': typeof DoctorInviteAcceptRoute
  '/management/history': typeof AuthenticatedManagementHistoryRoute
  '/management/': typeof AuthenticatedManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootstrap-admin': typeof BootstrapAdminRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/virtual-queue-guide': typeof VirtualQueueGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/pending-activation': typeof AuthenticatedPendingActivationRoute
  '/blog/virtual-vs-physical-queues': typeof BlogVirtualVsPhysicalQueuesRoute
  '/book/$slug': typeof BookSlugRoute
  '/doctor-invite/accept': typeof DoctorInviteAcceptRoute
  '/management/history': typeof AuthenticatedManagementHistoryRoute
  '/management': typeof AuthenticatedManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/bootstrap-admin': typeof BootstrapAdminRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/virtual-queue-guide': typeof VirtualQueueGuideRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/management': typeof AuthenticatedManagementRouteWithChildren
  '/_authenticated/pending-activation': typeof AuthenticatedPendingActivationRoute
  '/blog/virtual-vs-physical-queues': typeof BlogVirtualVsPhysicalQueuesRoute
  '/book/$slug': typeof BookSlugRoute
  '/doctor-invite/accept': typeof DoctorInviteAcceptRoute
  '/_authenticated/management/history': typeof AuthenticatedManagementHistoryRoute
  '/_authenticated/management/': typeof AuthenticatedManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bootstrap-admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/virtual-queue-guide'
    | '/admin'
    | '/doctor'
    | '/management'
    | '/pending-activation'
    | '/blog/virtual-vs-physical-queues'
    | '/book/$slug'
    | '/doctor-invite/accept'
    | '/management/history'
    | '/management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap-admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/virtual-queue-guide'
    | '/admin'
    | '/doctor'
    | '/pending-activation'
    | '/blog/virtual-vs-physical-queues'
    | '/book/$slug'
    | '/doctor-invite/accept'
    | '/management/history'
    | '/management'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bootstrap-admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/virtual-queue-guide'
    | '/_authenticated/admin'
    | '/_authenticated/doctor'
    | '/_authenticated/management'
    | '/_authenticated/pending-activation'
    | '/blog/virtual-vs-physical-queues'
    | '/book/$slug'
    | '/doctor-invite/accept'
    | '/_authenticated/management/history'
    | '/_authenticated/management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BootstrapAdminRoute: typeof BootstrapAdminRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VirtualQueueGuideRoute: typeof VirtualQueueGuideRoute
  BlogVirtualVsPhysicalQueuesRoute: typeof BlogVirtualVsPhysicalQueuesRoute
  BookSlugRoute: typeof BookSlugRoute
  DoctorInviteAcceptRoute: typeof DoctorInviteAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-queue-guide': {
      id: '/virtual-queue-guide'
      path: '/virtual-queue-guide'
      fullPath: '/virtual-queue-guide'
      preLoaderRoute: typeof VirtualQueueGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap-admin': {
      id: '/bootstrap-admin'
      path: '/bootstrap-admin'
      fullPath: '/bootstrap-admin'
      preLoaderRoute: typeof BootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-invite/accept': {
      id: '/doctor-invite/accept'
      path: '/doctor-invite/accept'
      fullPath: '/doctor-invite/accept'
      preLoaderRoute: typeof DoctorInviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/virtual-vs-physical-queues': {
      id: '/blog/virtual-vs-physical-queues'
      path: '/blog/virtual-vs-physical-queues'
      fullPath: '/blog/virtual-vs-physical-queues'
      preLoaderRoute: typeof BlogVirtualVsPhysicalQueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pending-activation': {
      id: '/_authenticated/pending-activation'
      path: '/pending-activation'
      fullPath: '/pending-activation'
      preLoaderRoute: typeof AuthenticatedPendingActivationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management': {
      id: '/_authenticated/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthenticatedManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/': {
      id: '/_authenticated/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof AuthenticatedManagementIndexRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/history': {
      id: '/_authenticated/management/history'
      path: '/history'
      fullPath: '/management/history'
      preLoaderRoute: typeof AuthenticatedManagementHistoryRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
  }
}

interface AuthenticatedManagementRouteChildren {
  AuthenticatedManagementHistoryRoute: typeof AuthenticatedManagementHistoryRoute
  AuthenticatedManagementIndexRoute: typeof AuthenticatedManagementIndexRoute
}

const AuthenticatedManagementRouteChildren: AuthenticatedManagementRouteChildren =
  {
    AuthenticatedManagementHistoryRoute: AuthenticatedManagementHistoryRoute,
    AuthenticatedManagementIndexRoute: AuthenticatedManagementIndexRoute,
  }

const AuthenticatedManagementRouteWithChildren =
  AuthenticatedManagementRoute._addFileChildren(
    AuthenticatedManagementRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedManagementRoute: typeof AuthenticatedManagementRouteWithChildren
  AuthenticatedPendingActivationRoute: typeof AuthenticatedPendingActivationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedManagementRoute: AuthenticatedManagementRouteWithChildren,
  AuthenticatedPendingActivationRoute: AuthenticatedPendingActivationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BootstrapAdminRoute: BootstrapAdminRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VirtualQueueGuideRoute: VirtualQueueGuideRoute,
  BlogVirtualVsPhysicalQueuesRoute: BlogVirtualVsPhysicalQueuesRoute,
  BookSlugRoute: BookSlugRoute,
  DoctorInviteAcceptRoute: DoctorInviteAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
